name: Deploy static HTML to Pages

on:
  push:
    branches: [$default-branch, 'refactor-b']

  # allow manual runs from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby 3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Fetch initial site assets
        run: ruby nix.rb --init https://raw.githubusercontent.com/nicholaswmin/nix/8e50218e5a219c260b4d4e3e43c97ef91682227c/init.yml
        
      - name: Build static HTML pages
        run: ruby nix.rb --build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # must match value of `_config.yml`:`dest`
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
