name: Deploy static HTML to Pages

on:
  push:
    branches: [$default-branch, 'refactor-b']

  # allow manual runs from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby 3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Setup Pages
        uses: actions/configure-pages@v5


      - name: Init sample
        run: ruby nix.rb -i "https://raw.githubusercontent.com/nicholaswmin/nix/main/init.yml"

      - name: Build Pages
        run: ruby nix.rb

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # must match value of `_config.yml`:`dest`
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
